django_practice/django_practice/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('practice.urls')),
]

django_practice/practice/urls.py
from django.urls import path

from . import views

app_name = 'practice'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_post/', views.add_post, name='add_post'),
    path('delete_post/<post_id>/', views.delete_post, name='delete_post'),
]

django_practice/practice/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField('Заголовок', max_length=100)
    text = models.TextField('Текст поста')
    author = models.CharField('Автор', max_length=100)
    pub_date = models.DateTimeField('Дата публикации', auto_now=True)
    count_likes = models.IntegerField('Количество лайков')

    def __str__(self):
        return self.title

django_practice/practice/forms.py
from django import forms

class AddPostForm(forms.Form):
    add_title = forms.CharField(label='Заголовок поста', max_length=100)
    add_text = forms.CharField(label='Текст поста', max_length=100)
    add_author = forms.CharField(label='Автор поста', max_length=100)
    add_count_likes = forms.IntegerField(label='Количество лайков')

django_practice/practice/views.py
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect
from .models import Post
from .forms import AddPostForm
from django.urls import reverse



def index(request):
    post_list = Post.objects.values()
    post_form = AddPostForm()
    return render(request, "practice/index.html", {'post_list': post_list, "form": post_form})


def add_post(request):
    if request.method == "POST":
        Post.objects.create(
            title=request.POST["add_title"],
            text=request.POST["add_text"],
            author=request.POST["add_author"],
            count_likes=request.POST["add_count_likes"]
        )
    return HttpResponseRedirect(reverse('practice:index'))


def delete_post(request, post_id=None):
    post_delete = Post.objects.get(id=post_id)
    post_delete.delete()
    return HttpResponseRedirect(reverse('practice:index'))

django_practice/practice/templates/practice/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Блог</title>
</head>
<body>
<h2>Список постов</h2>
{%block content%}
{% for i in post_list%}
<div>
    <p>Заголовок: {{i.title}} </p>
<p>Автор:{{i.author}}</p>
<p>Дата публикации:{{i.pub_date}}</p>
    <p>Текст:<br>{{i.text}}</p>
    <p>Количество лайков:{{i.count_likes}}</p>
<p><a href="{% url 'practice:delete_post' i.id %}">Удалить пост</a></p>
    </div>
    <hr>
{%endfor%}
    <hr>
<h2>Добавление поста</h2>
<form action="{% url 'practice:add_post' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button
                    type="submit">Добавить пост
            </button>
        </form>
{%endblock%}

</body>
</html>